from .user_service import create_ticket_service,get_ticket_list_service,get_ticket_detail_service,close_ticket_service,submit_review_service,timeline_service
from .agent_service import (accept_ticket_service,reject_ticket_service,get_agent_ticket_requests_service,get_agent_ticket_detail_service,
        get_agent_ongoing_tickets_service,resolve_ticket_service,reopen_ticket_service)
from .attach_sla_to_ticket import attach_sla_to_ticket
from .escalation_service import escalate_ticket_service
from .profile_service import get_profile_service,update_profile_service
from .team_lead_service import get_team_lead_tickets_service
from .manager_service  import get_manager_tickets_service
from .upload_client_doc_service import upload_client_doc_service,get_clients_with_documents,get_client_documents
from .summarize_service import summarize_document_service,submit_summary_service
from .team_lead_summary_service import get_teamlead_summaries_service,generate_agent_summary_service,submit_agent_summary_service,agent_summary_service
from .dashboard_service import dashboard_service
# from .agent_session_service import start_session_service,heartbeat_service,end_session_service
from .generate_fake_ticket_service import generate_fake_ticket_service
from .agent_pages import fetch_fake_tickets_service,get_fake_ticket_detail_service
from .auto_assign_service import auto_assign_service
from .chat_service import get_messages_service,send_message_service