version: "3.9"

services:

  web:
    build: .

    container_name: trs_backend

    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3

    env_file:
      - .env.docker

    volumes:
      - .:/app
      - static_volume:/app/staticfiles

    ports:
      - "8000:8000"

    depends_on:
      - redis

  redis:
    image: redis:7-alpine

    container_name: trs_redis

    ports:
      - "6379:6379"

volumes:
  static_volume: