services:

  web:
    build: .

    image: trs-backend:latest

    container_name: trs_backend

    restart: unless-stopped

    command: gunicorn core.wsgi:application \
      --bind 0.0.0.0:8000 \
      --workers 3

    env_file:
      - .env.production

    volumes:
      - static_volume:/app/staticfiles

    expose:
      - "8000"
    
  celery:
    image: trs-backend:latest

    restart: unless-stopped

    command: celery -A core worker -l info

    env_file:
      - .env.production