import requests
import os
import re
import json
from rest_framework import status
from apps.tickets.models import Ticket,TicketAssignment

OPENROUTER_API_KEY=os.getenv('OPENROUTER_API_KEY')

def generate_tickets_from_summary(summary, num_tickets=3):
    url = "https://openrouter.ai/api/v1/chat/completions"
    
    payload = {
        "model": "anthropic/claude-3-haiku:2024-11-20",
        "messages": [{"role": "user", "content": f"""Generate EXACTLY {num_tickets} tickets for: {summary}

CRITICAL: Respond with ONLY valid JSON array. NO prose, NO markdown, NO explanation.

[
  {{"title": "Payment Issue", "description": "Cannot process...", "priority": "HIGH", "category": "Payment"}},
  {{"title": "Login Error", "description": "Cannot login...", "priority": "MEDIUM", "category": "Auth"}}
]"""}]
    }
    
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": "http://localhost:3000", 
        "X-Title": "TRS Ticket System"
    }
    
    response = requests.post(url, json=payload, headers=headers)
    if response.status_code != 200:
        raise Exception(f'AI Error: {response.text}')
    
    data = response.json()
    content = data['choices'][0]['message']['content']
    return content

def parse_ai_ticket_response(ai_response):
    
    # Strip common prefixes Claude adds
    clean_response = ai_response.strip()
    if clean_response.startswith('```json'):
        json_match = re.search(r'```json\s*(.*?)\s*```', ai_response, re.DOTALL)
        json_str = json_match.group(1) if json_match else ai_response
    elif clean_response.startswith('['):
        json_str = ai_response
    else:
        # Extract JSON array from text
        json_match = re.search(r'\[.*\]', ai_response, re.DOTALL)
        json_str = json_match.group(0) if json_match else ai_response
        
    tickets = json.loads(json_str)
    
    # Handle both [{"tickets": [...]}] and [...]
    if isinstance(tickets, dict) and 'tickets' in tickets:
        tickets = tickets['tickets']
    
    if not isinstance(tickets, list):
        raise ValueError(f'Expected list, got {type(tickets)}')
    
    validated = []
    for i in tickets:
        validated.append({
            'title': i.get('title', ''),
            'description': i.get('description', ''),
            'priority': i.get('priority', 'MEDIUM'),
            'category': i.get('category', 'General'),
        })
    
    return validated

def parse_ai_ticket_response(ai_response):
    json_match = re.search(r'```json\s*(.*?)\s*```', ai_response, re.DOTALL)
    if json_match:
        json_str = json_match.group(1)
    else:
        json_str = ai_response
    try:
        tickets= json.loads(json_str)
        if not isinstance(tickets,list):
            raise ValueError('Response is not a list')
        validated=[]
        for i in tickets:
            validated.append({
                'title':i.get('title',''),
                'description':i.get('description',''),
                'priority':i.get('priority',''),
                'category':i.get('category',''),
            })
        return validated
    except json.JSONDecodeError:
        raise ValueError('Invalid JSON from AI')


def generate_fake_ticket_service(request):
    try:
        summary = request.data.get('summary')
        count = request.data.get('count', 3)
        
        if not summary:
            return {
                'data': {},
                'errors': {"details": 'summary is required'},
                'status': status.HTTP_400_BAD_REQUEST
            }
        
        team_lead = request.user  # Team Lead
        
        # Get all active, unblocked agents under this Team Lead
        agents = team_lead.agents.filter(role='AGENT', is_active=True, is_blocked=False)
        if not agents.exists():
            return {'data': {}, 'errors': {"details": 'No agents under this Team Lead'}, 'status': 400}
        
        # Generate tickets using AI
        ai_response = generate_tickets_from_summary(summary, count)
        tickets_data = parse_ai_ticket_response(ai_response)
        print(len(tickets_data))  # should be 5
        print([t['title'] for t in tickets_data])
        print(len(agents))        # should be total active agents
        if not tickets_data:
            return {'data': {}, 'errors': {"details": 'No tickets generated by AI'}, 'status': 500}
        
        created_ticket_ids = []
        assignment_ids = []
        if not team_lead.clients.exists():
            return {'data': {}, 'errors': {"details": "No client assigned to Team Lead"}, 'status': 400}
        client = team_lead.clients.first()

        # ✅ Create one ticket per AI-generated ticket
        for t in tickets_data:
            ticket_obj = Ticket.objects.create(
                subject=t["title"],
                description=t["description"],
                priority=t["priority"],
                issue_type=t["category"],
                client_id=client.id,
                created_by_id=team_lead.id,
                is_ai_generated=True
            )
            created_ticket_ids.append(ticket_obj.id)

            # ✅ Assign ticket to all agents
            for agent in agents:
                assignment = TicketAssignment.objects.create(
                    ticket=ticket_obj,
                    agent=agent,
                    status='ACCEPTED'
                )
                assignment_ids.append(assignment.id)
        
        return {
            'data': {
                "message": f"Created {len(created_ticket_ids)} tickets and assigned to {agents.count()} agents",
                "ticket_ids": created_ticket_ids,
                "assignment_ids": assignment_ids
            },
            "errors": {},
            'status': status.HTTP_201_CREATED
        }
    
    except Exception as e:
        import traceback
        print(traceback.format_exc())
        return {
            'data': {},
            'errors': {"details": str(e)},
            'status': status.HTTP_500_INTERNAL_SERVER_ERROR
        }