# Generated by Django 6.0.2 on 2026-03-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_ticket_code_ticketassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketassignment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
