# Generated by Django 6.0.2 on 2026-03-20 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_subscriptionplan_clientprofile_slapolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketslatracking',
            name='reassign_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tickets', to='tickets.clientprofile'),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
