# Generated by Django 6.0.2 on 2026-03-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_clientdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='extra_doc',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='faq_doc',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='guidelines_doc',
            field=models.URLField(),
        ),
    ]
