# Generated by Django 6.0.2 on 2026-04-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_clientdocument_extra_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
