# Generated by Django 6.0.2 on 2026-04-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_clientdocument_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdocument',
            name='status',
        ),
    ]
