# Generated by Django 6.0.2 on 2026-04-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_documentsummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsummary',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='summary_type',
            field=models.CharField(choices=[('manager', 'Manager Summary'), ('agent', 'Agent Summary')], default='manager', max_length=20),
            preserve_default=False,
        ),
    ]
