# Generated by Django 6.0.2 on 2026-04-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_alter_documentsummary_summary_type_agentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
