# Generated by Django 6.0.2 on 2026-05-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_ticket_is_ai_generated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentSession',
        ),
    ]
