# Generated by Django 6.0.2 on 2026-02-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_agentapplication_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentapplication',
            name='experience',
        ),
    ]
