# Generated by Django 6.0.2 on 2026-02-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_remove_agentapplication_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(default='SIGNUP', max_length=20),
        ),
    ]
