# Generated by Django 6.0.2 on 2026-02-16 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_emailotp_is_verified_emailotp_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentapplication',
            name='certificates',
        ),
        migrations.CreateModel(
            name='AgentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core_app.agentapplication')),
            ],
        ),
    ]
