# Generated by Django 6.0.2 on 2026-02-16 08:35

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_remove_agentapplication_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentapplication',
            name='resume',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='agentcertificate',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificates/'),
        ),
    ]
