# Generated by Django 6.0.2 on 2026-06-17 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='clients.clientprofile'),
        ),
    ]
