# Generated by Django 6.0.2 on 2026-07-02 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientprofile_app_url'),
        ('users', '0002_alter_clientuser_client_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='clientuser',
            constraint=models.UniqueConstraint(fields=('user', 'client_profile'), name='unique_user_client'),
        ),
    ]
