# Generated by Django 6.0.2 on 2026-07-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_clientuser_user_clientuser_unique_user_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='external_user_id',
        ),
    ]
