# Generated by Django 6.0.2 on 2026-06-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0009_ticket_ai_customer_prompt_ticket_is_training_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('AGENT', 'Agent'), ('AI_CUSTOMER', 'AI Customer')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_messages', to='tickets.ticket')),
            ],
        ),
    ]
