from .admin_service import (update_agent_profile_service)
from .agent_pages import fetch_fake_tickets_service,get_fake_ticket_detail_service
from .agent_service import (accept_ticket_service,reject_ticket_service,get_agent_ticket_requests_service,get_agent_ticket_detail_service,
        get_agent_ongoing_tickets_service)
from .agent_summary_service import agent_summary_service
