# Listening Port
listening-port=3478

# Listen on all interfaces
listening-ip=0.0.0.0

external-ip=13.205.216.174

# relay-ip=172.17.0.1

# Realm
realm=trs.prithvirajpu.online

# Authentication
lt-cred-mech
user=trs:trs123

# Fingerprint
fingerprint

# Disable STUN-only mode
no-stun-backward-compatibility

# Relay port range
min-port=49160
max-port=49200

# Logging
verbose
simple-log

# Don't expose software version
no-cli

