# Generated by Django 6.0.2 on 2026-06-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_certified_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='training_completed',
            field=models.BooleanField(default=False),
        ),
    ]
