# Generated by Django 6.0.2 on 2026-06-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
