# Generated by Django 6.0.2 on 2026-07-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_stripe_connect_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
