# Generated by Django 6.0.2 on 2026-07-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='app_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
