# Generated by Django 6.0.2 on 2026-06-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('INCENTIVE', 'Incentive'), ('BONUS', 'Bonus'), ('WITHDRAWAL', 'Withdrawal'), ('ADJUSTMENT', 'Adjustment')], max_length=30),
        ),
        migrations.CreateModel(
            name='SalaryPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='IncentiveCredit',
        ),
    ]
