# Generated by Django 6.0.2 on 2026-07-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_withdrawalrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('INCENTIVE', 'Incentive'), ('BONUS', 'Bonus'), ('WITHDRAWAL', 'Withdrawal'), ('PENALTY', 'Penalty'), ('ADJUSTMENT', 'Adjustment')], max_length=30),
        ),
    ]
