# Generated by Django 6.0.2 on 2026-09-25 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_salarydistributionconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarydistributionconfig',
            name='manager_salary',
        ),
        migrations.RemoveField(
            model_name='salarydistributionconfig',
            name='team_lead_salary',
        ),
        migrations.AddField(
            model_name='salarydistributionconfig',
            name='manager_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='salarydistributionconfig',
            name='team_lead_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='salarydistributionconfig',
            name='agent_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='salarydistributionconfig',
            name='incentive_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
