# Generated by Django 6.0.2 on 2026-06-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
