# Generated by Django 6.0.2 on 2026-07-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_agentapplication_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentapplication',
            name='reviewed_at',
        ),
    ]
