# Generated by Django 6.0.2 on 2026-05-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(choices=[('ORDER_ISSUE', 'Order Issue'), ('PAYMENT_ISSUE', 'Payment Issue'), ('REFUND_ISSUE', 'Refund Issue'), ('DELIVERY_ISSUE', 'Delivery Issue'), ('WALLET_ISSUE', 'Wallet Issue'), ('PRODUCT_ISSUE', 'Product Issue')], default='ORDER_ISSUE', max_length=100),
        ),
    ]
