# Generated by Django 6.0.2 on 2026-05-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_issue_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slapolicy',
            name='auto_reassign',
        ),
        migrations.RemoveField(
            model_name='slapolicy',
            name='max_reassign_attempts',
        ),
    ]
