# Generated by Django 6.0.2 on 2026-06-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_clientprofile_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketchat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketchat',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
