# Generated by Django 6.0.2 on 2026-06-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_customer_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_training_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='training_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='training_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='training_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('WELCOME_ACCOUNT_CREATED', 'welcome account created'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('TICKET_ESCALATED', 'Ticket Escalated'), ('TICKET_RESOLVED', 'Ticket Resolved'), ('MISSED_CALL', 'Missed Call'), ('TICKET_REOPENED', 'ticket reopened'), ('CHAT_MESSAGE', 'Chat Message')], max_length=50),
        ),
    ]
