# Generated by Django 6.0.2 on 2026-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_ai_customer_prompt_ticket_is_training_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='training_passed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
