# Generated by Django 6.0.2 on 2026-06-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticket_training_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketassignment',
            name='training_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='training_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='training_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='training_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NOT_STARTED', max_length=20),
        ),
    ]
