# Generated by Django 6.0.2 on 2026-06-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticketassignment_training_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='training_feedback',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='training_passed',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='training_score',
        ),
    ]
