# Generated by Django 6.0.2 on 2026-06-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_remove_ticket_training_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='internal_api_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='sso_shared_secret',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
