# Generated by Django 6.0.2 on 2026-06-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_clientprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
