# Generated by Django 6.0.2 on 2026-06-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_remove_clientprofile_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
