# Generated by Django 6.0.2 on 2026-06-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_clientsubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
