# Generated by Django 6.0.2 on 2026-06-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_clientsubscription_current_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCEL_SCHEDULED', 'Cancel_scheduled'), ('PAST_DUE', 'Past Due'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
