# Generated by Django 6.0.2 on 2026-06-17 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('tickets', '0021_alter_clientsubscription_status'),
        ('users', '0002_alter_clientuser_client_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsubscription',
            name='client',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tickets', to='clients.clientprofile'),
        ),
        migrations.RemoveField(
            model_name='clientsubscription',
            name='plan',
        ),
        migrations.AlterUniqueTogether(
            name='incentivecredit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='incentivecredit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='incentivecredit',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='incentivecredit',
            name='user',
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='clients.subscriptionplan'),
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.DeleteModel(
            name='ClientSubscription',
        ),
        migrations.DeleteModel(
            name='IncentiveCredit',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
