# Generated by Django 6.0.2 on 2026-07-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientprofile_app_url'),
        ('tickets', '0022_remove_clientsubscription_client_alter_ticket_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clients.clientprofile'),
        ),
    ]
