# Generated by Django 6.0.2 on 2026-03-11 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_subscriptionplan_clientprofile_slapolicy_and_more'),
        ('users', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tickets.clientprofile'),
        ),
    ]
